### ISSUE TITLE
If site admin log in as Student  account, the collapsed data won't display

### ISSUE THREAD

**Issue by chens2i** [PhilDevine/moodle-mod_labelcollapsed#12]
If site administrator log in as Student  account, then the collapsed data won't display.
Testing on Moodle version 3.9.8.
Use Lambda Moodle theme, version 1.98.22, release on 20210524.

**Comment by PhilDevine** [comment]
Hi Chens2i, I believe this is because of Moodle security, in that, JS is disabled when you login as another user, as an admin. If you use 'change role' to 'student' all works fine. My plugin in user interface (not settings) only accesses bootstrap from moodle core, no other javascript. Thanks you!

**Comment by tonyjbutler** [comment]
Hi Phil, https://github.com/PhilDevine/moodle-mod_labelcollapsed/pull/13 should fix this.

**Comment by PhilDevine** [comment]
Thanks Tony!

**Comment by tonyjbutler** [comment]
PR merged, closing,
