### ISSUE TITLE
Incorrect repository name

### ISSUE THREAD

**Issue by danmarsden** [PhilDevine/moodle-mod_labelcollapsed#2]
Please note this was previously reported in the review here:
https://tracker.moodle.org/browse/CONTRIB-8423
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

**Comment by PhilDevine** [comment]
Thanks Dan, now changed to reference frankenstylepluginname to my best understanding at this time. Cheers.

**Comment by danmarsden** [comment]
looks good to me! - :-)

**Comment by PhilDevine** [comment]
Cheers Dan! :)
