### ISSUE TITLE
incorrect link to source control repository in moodle.org plugins db entry.

### ISSUE THREAD

**Issue by danmarsden** [PhilDevine/moodle-mod_labelcollapsed#3]
as reported in https://tracker.moodle.org/browse/CONTRIB-8423
Source control URL and bug tracker URL must be set and valid. The current value "https://github.com/PhilDevine?tab=repositories" is not valid.

**Comment by PhilDevine** [comment]
Hi Dan, this has now been changed in Moodle.org to point direct to my github plugin repository.

**Comment by danmarsden** [comment]
cool - feel free to close these trackers when you think you've got them sorted!

**Comment by PhilDevine** [comment]
Cheers
