### ISSUE TITLE
missing thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [PhilDevine/moodle-mod_labelcollapsed#4]
Note this was also reported in https://tracker.moodle.org/browse/CONTRIB-8423

When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by PhilDevine** [comment]
Hi Dan, I've added a thirdpartylibs.xml in lib directory and readme txt. Thanks.

**Comment by danmarsden** [comment]
Hey Phil - that file needs to be in the root of your plugin dir - not in the folder "lib" - thanks!

**Comment by danmarsden** [comment]
but - I'd drop both your js files for the colourpicker thing into their own dir, and then reference that directory in the thirdpartylibs.xml file - that way it will exclude both js files from the codechecker tests.

**Comment by PhilDevine** [comment]
Cheers

**Comment by danmarsden** [comment]
yeah - that looks better and meets the requirements for hte plugins db approval - the minimised version of the js isn't included in that xml though so Moodle's codechecker will still be running through that version - usually I put stuff in a specific folder eg:
js/colourpicker/*.js and then in the thirdpartylibs.xml I set the location tag to just the folder name (js/colourpicker) - that way all files are excluded by Moodle tests.

**Comment by PhilDevine** [comment]
Cheers Dan, will look to do that, not just ./js
