### ISSUE TITLE
incorrect location used for JS

### ISSUE THREAD

**Issue by danmarsden** [PhilDevine/moodle-mod_labelcollapsed#5]
as reported in CONTRIB-8423
Coding style: Moodle coding guidelines should be followed to make the code easier to review and understand. JS should be ideally included via AMD modules. - Please see moodle's docs site for information on using JS in Moodle.

**Comment by PhilDevine** [comment]
Hi Dan, still working on this one, need to skill up more on AMD! I did try requirejs, but decided against requirejs as a method as kept getting conflicts, errors. The JS I have is a 3rd party lib so now referenced in lib directory. Other than that I have approx 5 lines of JS in mod_form that call the JS 3rd party lib. The plugin is a very small development, so not sure if it would benefit from AMD?

**Comment by danmarsden** [comment]
yeah - it's not a requirement/blocker for approval - just a nice to have.

**Comment by PhilDevine** [comment]
Cheers
