### ISSUE TITLE
styles.css not specific enough.

### ISSUE THREAD

**Issue by danmarsden** [PhilDevine/moodle-mod_labelcollapsed#6]
As mentioned in https://tracker.moodle.org/browse/CONTRIB-8423

in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by PhilDevine** [comment]
Great advice Dan, I've now used the Moodle Mod class style to identify active element. Thanks.
