### ISSUE TITLE
consider adding github action tests.

### ISSUE THREAD

**Issue by danmarsden** [PhilDevine/moodle-mod_labelcollapsed#9]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/main/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by PhilDevine** [comment]
Cool! Thanks for advice Dan. Will add, cheers :)

**Comment by danmarsden** [comment]
Doesn't look like you've used the Moodle action config but your own one? - ideally you should copy the example version here:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml

that way it will run the same tests that Moodle.org plugins db does on every commit - see the code precheck report accessible on this page:
https://moodle.org/plugins/mod_labelcollapsed/versions

**Comment by PhilDevine** [comment]
Cheers, my mistake!
